"""
SML Scanner - PDF Report Generator
=====================================
Renders aggregated ExecResult objects into a structured PDF using reportlab.
Layout: cover page -> executive summary table -> per-category sections ->
per-tool raw output (truncated + monospace) -> appendix with full commands run.
"""

import datetime
from pathlib import Path

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    PageBreak, Preformatted, NextPageTemplate, PageTemplate, Frame,
    BaseDocTemplate,
)
from reportlab.lib.enums import TA_CENTER

from .tools_config import Category
from .utils import ExecResult

MAX_RAW_CHARS = 6000  # per-tool output truncation to keep PDF size sane

STATUS_COLOR = {
    "ok": colors.HexColor("#1a7f37"),
    "timeout": colors.HexColor("#b08800"),
    "missing_binary": colors.HexColor("#6e7781"),
    "error": colors.HexColor("#cf222e"),
}
STATUS_LABEL = {
    "ok": "Completed",
    "timeout": "Timed Out",
    "missing_binary": "Skipped (tool not installed)",
    "error": "Error",
}


def _styles():
    ss = getSampleStyleSheet()
    ss.add(ParagraphStyle(name="SMLTitle", fontSize=26, leading=32, spaceAfter=6,
                           alignment=TA_CENTER, textColor=colors.HexColor("#0d1117")))
    ss.add(ParagraphStyle(name="SMLSubtitle", fontSize=13, leading=18,
                           alignment=TA_CENTER, textColor=colors.HexColor("#57606a")))
    ss.add(ParagraphStyle(name="SMLSection", fontSize=16, leading=20, spaceBefore=18,
                           spaceAfter=8, textColor=colors.HexColor("#0d1117")))
    ss.add(ParagraphStyle(name="SMLToolHead", fontSize=11.5, leading=14, spaceBefore=10,
                           spaceAfter=4, textColor=colors.white, backColor=colors.HexColor("#24292f"),
                           borderPadding=(4, 4, 4, 4)))
    ss.add(ParagraphStyle(name="SMLMeta", fontSize=9, leading=12, textColor=colors.HexColor("#57606a")))
    ss.add(ParagraphStyle(name="SMLCode", fontName="Courier", fontSize=7.5, leading=9.5,
                           textColor=colors.HexColor("#1f2328"), backColor=colors.HexColor("#f6f8fa")))
    return ss


def _truncate(text: str, limit: int = MAX_RAW_CHARS) -> str:
    if not text:
        return "(no output captured)"
    if len(text) <= limit:
        return text
    cut = text[:limit]
    return cut + f"\n\n... [truncated — {len(text) - limit} additional characters omitted] ..."


def build_report(
    target: str,
    results: list[ExecResult],
    output_path: str,
    scan_started: datetime.datetime,
    scan_finished: datetime.datetime,
    operator: str = "SML Scanner",
) -> str:
    """Build the PDF report and return the output path."""
    styles = _styles()
    doc = SimpleDocTemplate(
        output_path, pagesize=A4,
        topMargin=20 * mm, bottomMargin=18 * mm,
        leftMargin=16 * mm, rightMargin=16 * mm,
        title=f"SML Security Scan Report - {target}",
    )

    story = []

    # ---------- Cover ----------
    story.append(Spacer(1, 60))
    story.append(Paragraph("SML Security Scan Report", styles["SMLTitle"]))
    story.append(Paragraph(f"Target: {target}", styles["SMLSubtitle"]))
    story.append(Spacer(1, 30))

    duration = scan_finished - scan_started
    meta_rows = [
        ["Scan started", scan_started.strftime("%Y-%m-%d %H:%M:%S %Z") or scan_started.isoformat()],
        ["Scan finished", scan_finished.strftime("%Y-%m-%d %H:%M:%S %Z") or scan_finished.isoformat()],
        ["Total duration", str(duration).split(".")[0]],
        ["Tools executed", str(len(results))],
        ["Operator", operator],
    ]
    meta_table = Table(meta_rows, colWidths=[45 * mm, 100 * mm])
    meta_table.setStyle(TableStyle([
        ("FONTSIZE", (0, 0), (-1, -1), 9.5),
        ("TEXTCOLOR", (0, 0), (0, -1), colors.HexColor("#57606a")),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("LINEBELOW", (0, 0), (-1, -1), 0.5, colors.HexColor("#d0d7de")),
    ]))
    story.append(meta_table)
    story.append(Spacer(1, 20))
    story.append(Paragraph(
        "This report was generated by an automated tool for authorized security "
        "testing and lab use only. All scans were executed against a target the "
        "operator confirmed ownership of, or explicit written authorization for.",
        styles["SMLMeta"],
    ))
    story.append(PageBreak())

    # ---------- Executive Summary ----------
    story.append(Paragraph("Executive Summary", styles["SMLSection"]))
    summary_data = [["Tool", "Category", "Status", "Duration"]]
    for r in results:
        summary_data.append([
            r.display_name,
            _category_for(r.tool_key),
            STATUS_LABEL.get(r.status, r.status),
            f"{r.duration_sec:.1f}s" if r.status == "ok" else "-",
        ])
    summary_table = Table(summary_data, colWidths=[65 * mm, 45 * mm, 40 * mm, 20 * mm], repeatRows=1)
    style_cmds = [
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#24292f")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTSIZE", (0, 0), (-1, -1), 8.5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#d0d7de")),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f6f8fa")]),
    ]
    for i, r in enumerate(results, start=1):
        style_cmds.append(("TEXTCOLOR", (2, i), (2, i), STATUS_COLOR.get(r.status, colors.black)))
    summary_table.setStyle(TableStyle(style_cmds))
    story.append(summary_table)
    story.append(PageBreak())

    # ---------- Per-category sections ----------
    by_category: dict[str, list[ExecResult]] = {}
    for r in results:
        cat = _category_for(r.tool_key)
        by_category.setdefault(cat, []).append(r)

    for cat_name, cat_results in by_category.items():
        story.append(Paragraph(cat_name, styles["SMLSection"]))
        for r in cat_results:
            story.append(Paragraph(
                f"{r.display_name} &nbsp;&nbsp;|&nbsp;&nbsp; {STATUS_LABEL.get(r.status, r.status)}",
                styles["SMLToolHead"],
            ))
            story.append(Paragraph(f"Command: <font face='Courier'>{r.command}</font>", styles["SMLMeta"]))
            if r.status == "ok":
                story.append(Paragraph(
                    f"Exit code: {r.returncode} &nbsp;|&nbsp; Duration: {r.duration_sec:.1f}s",
                    styles["SMLMeta"],
                ))
                story.append(Spacer(1, 4))
                out = r.stdout.strip() or r.stderr.strip()
                story.append(Preformatted(_truncate(out), styles["SMLCode"]))
            elif r.status == "missing_binary":
                story.append(Paragraph(
                    "Tool binary was not found on PATH at scan time — install it and re-run "
                    "to include this section.", styles["SMLMeta"],
                ))
            elif r.status == "timeout":
                story.append(Paragraph(
                    f"Execution exceeded its {int(r.duration_sec)}s runtime and was terminated. "
                    "Partial output (if any) below.", styles["SMLMeta"],
                ))
                if r.stdout.strip():
                    story.append(Preformatted(_truncate(r.stdout.strip()), styles["SMLCode"]))
            else:
                story.append(Paragraph(f"Error: {r.stderr}", styles["SMLMeta"]))
            story.append(Spacer(1, 10))
        story.append(PageBreak())

    doc.build(story)
    return output_path


def _category_for(tool_key: str) -> str:
    from .tools_config import get_tool
    return get_tool(tool_key).category.value
